services:
  randomcoffee_bot:
    build: .
    container_name: randomcoffee_bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./random_coffee.db:/app/random_coffee.db  # База данных SQLite
      - ./.env:/app/.env  # Конфигурация
      - ./shared/logs:/app/shared/logs  # Логи
    env_file:
      - .env

